// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at ۱۴۰۳/۱۲/۱۲, ۱۰:۳۵:۰۶
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/etezadi/Desktop/projects/bale-game-qajar/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/etezadi/Desktop/projects/bale-game-qajar/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/etezadi/Desktop/projects/bale-game-qajar/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/etezadi/Desktop/projects/bale-game-qajar/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/etezadi/Desktop/projects/bale-game-qajar/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/etezadi/Desktop/projects/bale-game-qajar/plugins/**/*.{js,ts,mjs}","C:/Users/etezadi/Desktop/projects/bale-game-qajar/composables/**/*.{js,ts,mjs}","C:/Users/etezadi/Desktop/projects/bale-game-qajar/utils/**/*.{js,ts,mjs}","C:/Users/etezadi/Desktop/projects/bale-game-qajar/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/etezadi/Desktop/projects/bale-game-qajar/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/etezadi/Desktop/projects/bale-game-qajar/app.config.{js,ts,mjs}","C:/Users/etezadi/Desktop/projects/bale-game-qajar/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;